List Players
Identechal/flint pull request #10
Opened 2022-12-31 19:04 UTC by jacobbrokaw

Get a roster of online players and the limit.
This update includes an extensible class for supporting more commands.

2022-12-31 19:17 UTC, jacobbrokaw commented
While testing, I noticed that the response body of `GET` /api/server returns numbers as strings.
```json
{
    "status": {
        "name": "RUNNING",
        "canStart": false,
        "canStop": true
    },
    "list": {
        "online": "0", // should be a number
        "max": "3", // should be a number
        "roster": []
    }
}
```

2023-01-02 14:02 UTC, nicholasbrokaw requested changes

2023-01-02 14:02 UTC, nicholasbrokaw commented on src/models/mc/commands/list/Players.js
> +   * @param {number} count
```suggestion
   * @param {number} online
```

2023-01-02 15:46 UTC, nicholasbrokaw approved these changes

2023-01-02 15:47 UTC, merged