API Key Auth
Identechal/flint pull request #11
Opened 2023-02-26 15:57 UTC by jacobbrokaw

Authorize requests with API keys.

2023-02-26 16:05 UTC, jacobbrokaw commented
This update was originally going to include public key (asymmetric) authentication. However, work on this has been reverted, as I am not confident in my knowledge of the concept. I will continue to research and revisit it when I am comfortable.

2023-03-16 23:23 UTC, nicholasbrokaw requested changes

2023-03-16 23:41 UTC, nicholasbrokaw approved these changes

2023-03-16 23:41 UTC, merged

2024-09-04 07:32 UTC, Cynn1989 approved these changes